services:
  # PostgreSQL Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: vet-app-postgres-dev
    environment:
      POSTGRES_DB: vet_app_db
      POSTGRES_USER: ${DB_USER:-vet_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-vet_password}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - vet-app-network
    restart: unless-stopped

  # User Service (development mode with volume mounting)
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    container_name: vet-app-user-service-dev
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: vet_app_db
      DB_USER: ${DB_USER:-vet_user}
      DB_PASSWORD: ${DB_PASSWORD:-vet_password}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - vet-app-network
    restart: unless-stopped
    volumes:
      - ./user-service/src:/app/src
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # Pet Service (development mode)
  pet-service:
    build: 
      context: ./pet-service
      dockerfile: Dockerfile
    container_name: vet-app-pet-service-dev
    environment:
      NODE_ENV: development
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: vet_app_db
      DB_USER: ${DB_USER:-vet_user}
      DB_PASSWORD: ${DB_PASSWORD:-vet_password}
      USER_SERVICE_URL: http://user-service:3001
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - user-service
    networks:
      - vet-app-network
    restart: unless-stopped
    volumes:
      - ./pet-service/src:/app/src
      - /app/node_modules
    command: ["npm", "run", "dev"]

  # Notification Service (development mode)
  notification-service:
    build: 
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: vet-app-notification-service-dev
    environment:
      NODE_ENV: development
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: vet_app_db
      DB_USER: ${DB_USER:-vet_user}
      DB_PASSWORD: ${DB_PASSWORD:-vet_password}
      PET_SERVICE_URL: http://pet-service:3002
      USER_SERVICE_URL: http://user-service:3001
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_SECURE: ${EMAIL_SECURE:-false}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - user-service
      - pet-service
    networks:
      - vet-app-network
    restart: unless-stopped
    volumes:
      - ./notification-service/src:/app/src
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_dev_data:
    driver: local

networks:
  vet-app-network:
    driver: bridge